[package]
name = "Kra"
version = "0.1.0"
edition = "2021"

[dependencies]

redis = "0.25"
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.12", features = ["json", "stream", "rustls-tls"] }
zip = "0.6"
tempfile = "3"
walkdir = "2.5"